version: '3'

services:
  web:
    image: bhboruff/php-composer
    environment:
      user: "${UID}:${GID}"
      # NB: the default for PHP_OPCACHE_VALIDATE_TIMESTAMPS is 0, which may be what you
      # want for production, but for dev you certainly want file changes to be detected, thus set to 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    ports:
      - 8000:8000
    volumes:
      - .:/code
    # command: php -S 0.0.0.0:9000 .
    command: php artisan serve --host 0.0.0.0

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caltest
    volumes:
      - caltest_db:/var/lib/postgresql/data

volumes:
  caltest_db: